name: Project windows distribution

on:
  push:
    branches:
      - master

jobs:
  distribution:
    runs-on: windows-2019
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Poetry install
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Update PATH
        run: set PATH=%PATH%;C:\Users\runneradmin\AppData\Roaming\Python\Scripts
      - name: Poetry install
        run: poetry install
      - name: Create distribution
        run: pyinstaller src/aether/app.py
